routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index')->name('index');

Route::resource('bank', 'BankController');

Route::resource('calculation', 'CalculationController');

app/Bank.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bank extends Model
{
    protected $fillable = [
        'name',
        'rate',
        'loan',
        'payment',
        'term',
    ];

    public function calculations()
    {
        return $this->hasMany(Calculation::class);
    }
}

app/Calculation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Calculation extends Model
{
    protected $fillable = [
        'bank_id',
        'bank_name',
        'loan',
        'first_payment',
        'monthly_payment',
        'term',
        'rate',
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BankController.php
<?php

namespace App\Http\Controllers;

use App\Bank;
use Illuminate\Http\Request;

class BankController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $banks = Bank::orderBy('id', 'desc')->get();
        return view('banks.index', compact('banks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('banks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:255|min:5|unique:banks',
            'rate' => 'required|integer|max:100|min:1',
            'loan' => 'required|integer|max:1000000|min:10000',
            'payment' => 'required|integer|max:100|min:1',
            'term' => 'required|integer|max:120|min:12',
        ]);
        Bank::create($request->all());

        return redirect()->route('bank.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function show(Bank $bank)
    {
        return view('banks.show', compact('bank'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function edit(Bank $bank)
    {

        return view('banks.edit', compact('bank'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Bank $bank)
    {
        $request->validate([
            'name' => 'required|max:255|min:5',
            'rate' => 'required|integer|max:100|min:1',
            'loan' => 'required|integer|max:1000000|min:10000',
            'payment' => 'required|integer|max:100|min:1',
            'term' => 'required|integer|max:120|min:12',
        ]);

        $bank->update($request->all());

        return redirect()->route('bank.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Bank  $bank
     * @return \Illuminate\Http\Response
     */
    public function destroy(Bank $bank)
    {
        $bank->delete();

        return redirect()->route('bank.index');
    }
}

app/Http/Controllers/CalculationController.php
<?php

namespace App\Http\Controllers;

use App\Bank;
use App\Calculation;
use Illuminate\Http\Request;

class CalculationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $calculations = Calculation::orderBy('id', 'desc')->get();
        return view('calculations.index', compact('calculations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $banks = Bank::all();
        return view('calculations.create', compact('banks'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $bank = Bank::where('id', $request->bank_id)->first();

        $minFirstPayment = ($request->loan / 100) * $bank->payment;

        $request->validate([
            'loan' => 'required|integer|max:'. $bank->loan,
            'first_payment' => 'required|integer|min:' . $minFirstPayment,
        ]);

        $parameters = $request->all();
        $parameters['bank_name'] = $bank->name;
        $parameters['term'] = $bank->term;
        $parameters['rate'] = $bank->rate;

        $r = $bank->rate;
        $P = $request->loan;
        $n = $bank->term;

        $formula1 = $r / 12;
        $formula2 = (1 + $formula1) ** $n;
        $formula3 = $formula2 - 1;

        $monthlyPayment = ($P * $formula1 * $formula2) / $formula3;

        $parameters['monthly_payment'] = (int)$monthlyPayment;

        Calculation::create($parameters);

        return redirect()->route('calculation.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Calculation  $calculation
     * @return \Illuminate\Http\Response
     */
    public function show(Calculation $calculation)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Calculation  $calculation
     * @return \Illuminate\Http\Response
     */
    public function edit(Calculation $calculation)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Calculation  $calculation
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Calculation $calculation)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Calculation  $calculation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Calculation $calculation)
    {
        $calculation->delete();

        return redirect()->route('calculation.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class PageController extends Controller
{
    public function index()
    {
        return view('pages.index');
    }
}

resources/views/banks/create.blade.php
@extends('master')

@section('main')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <h2 class="display-6 text-center mb-4">Add new bank</h2>

    <div class="row row-cols-1 mb-3 text-center">
        <div class="col d-flex justify-content-center">
            <div class="card mb-4 rounded-3 shadow-sm w-75">
                <div class="card-body">
                    <form action="{{ route('bank.store') }}" method="post">
                        @csrf

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1">Name</span>
                            <input type="text" name="name" class="form-control" placeholder="min:5 | max:255 characters" aria-label="Username" aria-describedby="basic-addon1">
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon2">Interest rate</span>
                            <input type="text" name="rate" class="form-control" placeholder="min:1 | max:100" aria-label="Username" aria-describedby="basic-addon2">
                            <span class="input-group-text">%</span>
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon2">Maximum loan</span>
                            <input type="text" name="loan" class="form-control" placeholder="min:10 000 | max:1 000 000" aria-label="Username" aria-describedby="basic-addon2">
                            <span class="input-group-text">$</span>
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon2">Minimum down payment</span>
                            <input type="text" name="payment" class="form-control" placeholder="min:1 | max:100" aria-label="Username" aria-describedby="basic-addon2">
                            <span class="input-group-text">%</span>
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon2">Loan term</span>
                            <input type="text" name="term" class="form-control" placeholder="min:12 | max:120" aria-label="Username" aria-describedby="basic-addon2">
                            <span class="input-group-text">months</span>
                        </div>

                        <button type="submit" class="btn btn-success">Add</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/banks/edit.blade.php
@extends('master')

@section('main')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <h2 class="display-6 text-center mb-4">Edit {{ $bank->name }}</h2>

    <div class="row row-cols-1 mb-3 text-center">
        <div class="col d-flex justify-content-center">
            <div class="card mb-4 rounded-3 shadow-sm w-75">
                <div class="card-body">
                    <form action="{{ route('bank.update', $bank) }}" method="post">
                        @method('PUT')
                        @csrf

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1">Name</span>
                            <input type="text" name="name" value="{{ $bank->name }}" class="form-control" aria-label="Username" aria-describedby="basic-addon1">
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon2">Interest rate</span>
                            <input type="text" name="rate" value="{{ $bank->rate }}" class="form-control" aria-label="Username" aria-describedby="basic-addon2">
                            <span class="input-group-text">%</span>
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon2">Maximum loan</span>
                            <input type="text" name="loan" value="{{ $bank->loan }}" class="form-control" aria-label="Username" aria-describedby="basic-addon2">
                            <span class="input-group-text">$</span>
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon2">Minimum down payment</span>
                            <input type="text" name="payment" value="{{ $bank->payment }}" class="form-control" aria-label="Username" aria-describedby="basic-addon2">
                            <span class="input-group-text">%</span>
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon2">Loan term</span>
                            <input type="text" name="term" value="{{ $bank->term }}" class="form-control" aria-label="Username" aria-describedby="basic-addon2">
                            <span class="input-group-text">months</span>
                        </div>

                        <button type="submit" class="btn btn-warning">Edit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/banks/index.blade.php
@extends('master')

@section('main')
    <h2 class="display-6 text-center mb-4">Bank list</h2>

    <div class="text-center mb-4">
        <a href="{{ route('bank.create') }}" class="btn btn-success">Add new bank</a>
    </div>



    <div class="table-responsive">
        <table class="table text-center">
            <thead>
            <tr>
                <th style="width: 5%;">№</th>
                <th style="width: 15%;">Name</th>
                <th style="width: 15%;">Interest rate</th>
                <th style="width: 15%;">Max loan</th>
                <th style="width: 15%;">Min down payment</th>
                <th style="width: 15%;">Term</th>
                <th style="width: 20%;"></th>
            </tr>
            </thead>

            <tbody>

            @foreach($banks as $bank)
                <tr>
                    <th>{{ $bank->id }}</th>
                    <th>{{ $bank->name }}</th>
                    <td>{{ $bank->rate }}%</td>
                    <td>{{ $bank->loan }}$</td>
                    <td>{{ $bank->payment }}%</td>
                    <td>{{ $bank->term }} months</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a href="{{ route('bank.show', $bank) }}" class="btn btn-primary">Calculations</a>
                            <a href="{{ route('bank.edit', $bank) }}" class="btn btn-warning">Edit</a>
                            <form action="{{ route('bank.destroy', $bank) }}" method="post">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>

                        </div>

                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>
    </div>
@endsection

resources/views/banks/show.blade.php
@extends('master')

@section('main')
    <h2 class="display-6 text-center mb-4">Calculation history for {{ $bank->name }}</h2>

    <div class="table-responsive">
        <table class="table text-center">
            <thead>
            <tr>
                <th style="width: 5%;">№</th>
                <th style="width: 15%;">Bank</th>
                <th style="width: 15%;">Loan</th>
                <th style="width: 15%;">Down payment</th>
                <th style="width: 15%;">Monthly payment</th>
                <th style="width: 15%;">Rate</th>
                <th style="width: 10%;">Term</th>
                <th style="width: 10%;"></th>
            </tr>
            </thead>

            <tbody>

            @if($bank->calculations != null)
                @foreach($bank->calculations as $calculation)
                    <tr>
                        <th>{{ $calculation->id }}</th>
                        <th>{{ $calculation->bank_name }}</th>
                        <td>{{ $calculation->loan }}$</td>
                        <td>{{ $calculation->first_payment }}$</td>
                        <td>{{ $calculation->monthly_payment }}$</td>
                        <td>{{ $calculation->rate }}%</td>
                        <td>{{ $calculation->term }} months</td>
                        <td>
                            <div class="btn-group" role="group">
                                <form action="{{ route('calculation.destroy', $calculation) }}" method="post">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>

                            </div>

                        </td>
                    </tr>
                @endforeach
            @endif



            </tbody>
        </table>
    </div>
@endsection

resources/views/calculations/create.blade.php
@extends('master')

@section('main')

    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <h2 class="display-6 text-center mb-4">Monthly payment calculator</h2>

    <div class="row row-cols-1 mb-3 text-center">
        <div class="col d-flex justify-content-center">
            <div class="card mb-4 rounded-3 shadow-sm w-75">
                <div class="card-body">
                    <form action="{{ route('calculation.store') }}" method="post">
                        @csrf

                        <div class="form-floating mb-3">
                            <select name="bank_id" class="form-select" id="floatingSelect" aria-label="Floating label select example">
                                @foreach($banks as $bank)
                                    <option value="{{ $bank->id }}">
                                        {{ $bank->name }} | Interest rate: {{ $bank->rate }}% | Max loan: {{ $bank->loan }}$ | Minimum down payment: {{ $bank->payment }}% | Loan term: {{ $bank->term }} months
                                    </option>
                                @endforeach
                            </select>
                            <label for="floatingSelect">Choose a bank</label>
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon1">Initial loan</span>
                            <input type="text" name="loan" class="form-control" placeholder="200000" aria-label="Username" aria-describedby="basic-addon1">
                            <span class="input-group-text">$</span>
                        </div>

                        <div class="input-group mb-3">
                            <span class="input-group-text" id="basic-addon2">Down payment</span>
                            <input type="text" name="first_payment" class="form-control" placeholder="20000" aria-label="Username" aria-describedby="basic-addon2">
                            <span class="input-group-text">$</span>
                        </div>

                        <button type="submit" class="btn btn-primary">Calculate</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/calculations/index.blade.php
@extends('master')

@section('main')
    <h2 class="display-6 text-center mb-4">Calculation history</h2>

    <div class="text-center mb-4">
        <a href="{{ route('calculation.create') }}" class="btn btn-success">Calculator</a>
    </div>



    <div class="table-responsive">
        <table class="table text-center">
            <thead>
            <tr>
                <th style="width: 5%;">№</th>
                <th style="width: 15%;">Bank</th>
                <th style="width: 15%;">Loan</th>
                <th style="width: 15%;">Down payment</th>
                <th style="width: 15%;">Monthly payment</th>
                <th style="width: 15%;">Rate</th>
                <th style="width: 10%;">Term</th>
                <th style="width: 10%;"></th>
            </tr>
            </thead>

            <tbody>

            @if($calculations != null)
                @foreach($calculations as $calculation)
                    <tr>
                        <th>{{ $calculation->id }}</th>
                        <th>{{ $calculation->bank_name }}</th>
                        <td>{{ $calculation->loan }}$</td>
                        <td>{{ $calculation->first_payment }}$</td>
                        <td>{{ $calculation->monthly_payment }}$</td>
                        <td>{{ $calculation->rate }}%</td>
                        <td>{{ $calculation->term }} months</td>
                        <td>
                            <div class="btn-group" role="group">
                                <form action="{{ route('calculation.destroy', $calculation) }}" method="post">
                                    @method('DELETE')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>

                            </div>

                        </td>
                    </tr>
                @endforeach
            @endif



            </tbody>
        </table>
    </div>
@endsection

resources/views/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>MortgageCalculator</title>

    <!-- Font Awesome -->
    <link
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
        rel="stylesheet"
    />
    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <style>
        .footer {
            position: absolute;
            bottom: 0;
            left: 0;
            width: 100%;
        }
    </style>
</head>

<body>

<div class="container py-3">

    <header>
        <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
            <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
                <span class="fs-4"><i class="fas fa-home"></i> MortgageCalculator</span>
            </a>

            <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                <a class="me-3 py-2 text-dark text-decoration-none" href="{{ route('bank.index') }}">Banks</a>
                <a class="py-2 text-dark text-decoration-none" href="{{ route('calculation.index') }}">Calculations</a>
            </nav>
        </div>
    </header>

    <main>
        @yield('main')
    </main>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>


</body>
</html>

resources/views/pages/index.blade.php
@extends('master')

@section('main')
    <h2 class="display-6 text-center my-4">This is a web application where you can add banks and calculate mortgage payments for free.</h2>
    <h3 class="text-center mb-4">Determine what you could pay each month by using this mortgage calculator to calculate estimated monthly payments and rate options for a variety of loan terms.</h3>
@endsection